baseURL = 'https://atfzl.com/'
languageCode = 'en-us'
title = 'Atif Afzal'
theme = 'hugo-bearblog'

markup.highlight.codeFences = false
markup.goldmark.renderer.unsafe = true

[params]
  hideMadeWithLine = true
  favicon = "favicon.ico"
